Update index.md with new billing FAQ
antimetal/docs pull request #18
Opened 2024-05-22 17:28 UTC by anuraagr

2024-05-23 13:48 UTC, shreyas-iyer requested changes

2024-05-23 13:48 UTC, shreyas-iyer commented on docs/faq/index.md
> +</summary>
Would add more detail here regarding Stripe shows 8th-8th since that's when we send out invoices, but the invoices are always for a single month (i.e. April)

2024-05-23 15:02 UTC, anuraagr commented on docs/faq/index.md
> +</summary>
updated and added another faq.

2024-05-23 21:37 UTC, anuraagr commented on docs/faq/index.md
> +
@shreyas-iyer fixed and added a couple other faqs

2024-06-13 23:09 UTC, shreyas-iyer requested changes
Few minor nits

2024-06-13 23:09 UTC, shreyas-iyer commented on docs/faq/index.md
> +Antimetal invoices are sent on the 6th for infromation purposes while Stripe payments are processed on the 8th.
Misspelling

2024-06-13 23:09 UTC, shreyas-iyer commented on docs/faq/index.md
> +Invoices are issued for the charges from the most recent complete month (e.g., invoice sent on June 6th will be for the charges from May 1 ~ May 31).
The question here is on Stripe invoice dates. 

Let's change to the 8th (as that's when they go out)

2024-06-20 15:59 UTC, shreyas-iyer approved these changes

2024-06-20 15:59 UTC, merged